### PR TITLE
Chore: Remove obsolete lib/visitor-keys.js

### PR DESCRIPTION
**Pull request by matz3**
PR #389 deleted "lib/visitor-keys.js" and replaced all usages with the
eslint-visitor-keys package.
PR #387 added lib/visitor-keys.js back again for no apparent reason.

It looks like #387 has been started before #389, so it needed to
integrate those changes and by mistake the file has been added again.

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
good catch, thanks! LGTM, but I'd like one more reviewer.

**Comment by aladdin-add** [comment]
can you sign our cla, so we can merge it?

**Comment by matz3** [comment]
Signed 👍🏻

**Review by snitin315 — APPROVED** [review]
LGTM

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

That module is definitely unused now. Also, its content is old.

Since we have the `exports` field in package.json it can't be accessed, so it feels safe to remove the file.

**Comment by matz3** [comment]
Thanks!
Yeah we also got confused by the different content, which is why I tried to understand why the file still exists.

**Pull request merged**
