### PR TITLE
fix: Derive espree.Syntax from espree.VisitorKeys

### LINKED ISSUE #531: ChainExpression and others are missing in espree.Syntax
According to #331, the `espree.Syntax` object is supposed to contain all node types supported by Espree. But comparing it with ` espree.VisitorKeys`, the following node types are missing:

* `ChainExpression`
* `ImportExpression`
*  `JSXFragment`
*  `JSXOpeningFragment`
*  `JSXClosingFragment`
*  `PrivateIdentifier`
*  `PropertyDefinition`
*  `StaticBlock`

`ExperimentalRestProperty` and `ExperimentalSpreadProperty` are also missing, but this might be intentional.

For sure one could derive a list of node types from the keys of `VisitorKeys`, but what's the purpose of the `Syntax` export then? Shouldn't it be used any longer?

### PR DESCRIPTION
**Pull request by codeworrior**
Fixes #531.

If removing the `lib/ast-node-types.js` is regarded as an incompatible change, I can restore it and leave the cleanup up to you in one of the upcoming major releases. My assumption was that the module is rather an internal thing and not part of your APIs.

### CODE REVIEW

**Comment by codeworrior** [comment]
Sorry for not immediately signing the CLA. I have to clarify with my employer first.

**Review by nzakas — APPROVED** [review]
LGTM. Just want another set of eyes before merging.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

Waiting for CLA before merging.

**Comment by codeworrior** [comment]
Sorry for the delay. After my employer decided to sign the corporate CLA, we struggled a bit with the process and tooling, but now we're done.

**Comment by mdjermanovic** [comment]
Thanks for contributing!

**Pull request merged**
