### PR TITLE
Fix: lastToken not reset between calls to parse (fixes #229)

### LINKED ISSUE #229: lastToken not reset between calls to parse
lastToken is not initialized on each call to parse. This, together with some output options, can cause issues when parsing an empty file or one containing just comments.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29963166-lasttoken-not-reset-between-calls-to-parse?utm_campaign=plugin&utm_content=tracker%2F9348450&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9348450&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by nzakas** [comment]
Please check the travis build

**Comment by alberto** [comment]
I did. It's failing because of an unrelated issue. I don't know why build passes ok on my machine but it's failing on CI because of an duplicated config in eslint-config-eslint@1.0.1. The next release is 2.0.0, and in order to upgrade to it, eslint also needs to be upgraded to 2.0.0-beta.1. Do you want me to submit a PR to do that?

**Comment by nzakas** [comment]
Ah crap...yeah, could you do that? Sorry about the mess.

**Comment by nzakas** [comment]
I'll do it, I have some time right now.

**Pull request merged**
