### PR TITLE
When ecmaFeatures.forOf is true, check for operator is "undefined" when match keyword is "in" #39

### PR DESCRIPTION
**Pull request by peterkc**
Enable forOf
```
{ forOf: true }
```

Espree will error with "undefined" 
```
for (var k in console) {
    doSomething();
}
```

See test files in PR for examples.

### CODE REVIEW

**Comment by nzakas** [comment]
Nice catch. Can you update your commit summary so it has "(fixes #39)" at the end?

**Comment by peterkc** [comment]
Done

**Comment by nzakas** [comment]
Can you please sign our CLA here: http://eslint.org/cla

This just basically says that you're giving us permission to use your contribution.

**Comment by peterkc** [comment]
Done

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
