### PR TITLE
Added sudo false to travis to build faster

### PR DESCRIPTION
**Pull request by kahwee**
I noticed travis.yml didn't have sudo false. It could be faster using their docker containers. http://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks, per the readme, this repo follows the ESLint contribution guidelines: http://eslint.org/docs/developer-guide/contributing.html

That means we need an issue for each pull request, a specific commit format, and we need you to sign our CLA: http://eslint.org/cla

**Comment by kahwee** [comment]
Thanks for pointing that out. Sorry I've missed it. I've change the commit to fit the contributing guidelines.

**Comment by nzakas** [comment]
Thanks!

**Comment by nzakas** [comment]
Oops, can you put "fixes #177" instead of refs? That way, merging this will close the issue.

**Comment by kahwee** [comment]
Sure, done that. Thanks.

**Pull request merged**
