### PR TITLE
Update: Remove guardedHandlers/handlers from try (fixes #71)

### LINKED ISSUE #71: Remove TryStatement.handlers
Ref estree/estree#1:

```js
interface TryStatement <: Statement {
    // ....
    handler: CatchClause | null;
    handlers: [ CatchClause ]; // Removed
    // ....
}
```

The `handlers` array on `TryStatement` nodes was replaced with a single `handler`, which may be either a `CatchClause` or `null`.

#70 added support for the singular `handler` property. The next step is to remove `handlers`. This will be a breaking change.

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by btmills** [comment]
Isn't this a breaking change?

**Comment by nzakas** [comment]
Yup. Already updated the commit summary.

**Comment by btmills** [comment]
Ah, I missed that. :+1: LGTM.

**Comment by nzakas** [comment]
Thanks. Going to let this sit until I'm sure we don't need another patch release.

**Pull request merged**
