### PR TITLE
Update: Add TryStatement.handler (refs #69)

### PR DESCRIPTION
**Pull request by btmills**
This is a port of jquery/esprima#1034. It adds `handler` while leaving `handlers` unchanged. `handler` was decided upon in estree/estree#1.

### CODE REVIEW

**Comment by nzakas** [comment]
Lgtm. Can you update your commit message to use "fixes"?

**Comment by btmills** [comment]
Done. Do you want a separate issue to remove `handlers` as a breaking change later?

**Comment by nzakas** [comment]
Yes please.

**Comment by btmills** [comment]
Filed #71 for removal of `handlers`.

**Pull request merged**
