### PR TITLE
feat!: Require Node.js ^18.18.0 || ^20.9.0 || >=21.1.0

### PR DESCRIPTION
**Pull request by aladdin-add**
refs: https://github.com/eslint/eslint/issues/17595

~~blocked by https://github.com/eslint/espree/pull/590~~

### CODE REVIEW

**Comment by aladdin-add** [comment]
converting to draft - not sure why the test failed.

**Comment by nzakas** [comment]
Maybe a result of the Acorn bugs?

**Comment by nzakas** [comment]
Where are we on this?

**Comment by aladdin-add** [comment]
blocked by https://github.com/eslint/espree/pull/590, and it's blocked by acorn.

**Comment by nzakas** [comment]
Is there an Acorn issue we can track?

**Comment by aladdin-add** [comment]
seems no, will file one later.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
