### PR TITLE
Docs: added missing `ecmaFeatures.superInFunctions` option from doc

### PR DESCRIPTION
**Pull request by eTorAken**
Related to https://github.com/eslint/espree/issues/153

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks, can you update the commit message to begin with "Docs:" instead?

You can use `git commit --amend` and then do a forced push to your branch.

**Comment by eTorAken** [comment]
Will do!

**Comment by eTorAken** [comment]
Done, thanks for the tip!

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
