### PR TITLE
Upgrade: acorn to ^4.0.8

### PR DESCRIPTION
**Pull request by gyandeeps**
It was pinned to 4.0.4 before.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I think we should hold off on this at least until after ESLint release. Just to be safe

**Comment by mysticatea** [comment]
CI failed...

**Comment by ilyavolodin** [comment]
Looks like two error off by 1, and the same ES7 `use strict` issue.

**Comment by mysticatea** [comment]
Also, because of https://github.com/ternjs/acorn/issues/504, Several tests of ESLint have failed with Acorn 4.0.8.
E.g. [/tests/lib/rules/no-cond-assign.js#L52](https://github.com/eslint/eslint/blob/8ea98f9cc0c8444fcd38b6871ceb320067a5dc4b/tests/lib/rules/no-cond-assign.js#L52)

**Comment by gyandeeps** [comment]
closing for https://github.com/eslint/espree/pull/317

**Pull request closed without merging**
