### PR TITLE
ci: auto update sponsors in README

### PR DESCRIPTION
**Pull request by snitin315**
Cron job to update sponsors in README.

We need to enable the `secrets.WORKFLOW_PUSH_BOT_TOKEN` secret for this repo. Can someone with access do it?

### CODE REVIEW

**Comment by snitin315** [comment]
`npm install` step is failing for node v22, looking into it.

**Comment by fasttime** [comment]
> `npm install` step is failing for node v22, looking into it.

I think this is the same problem as in eslint CI, it's a bug in Node.js v.22.5.0.

**Comment by snitin315** [comment]
> > `npm install` step is failing for node v22, looking into it.
> 
> I think this is the same problem as in eslint CI, it's a bug in Node.js v.22.5.0.

Should we pin node.js version to v22.4.0?

**Comment by mdjermanovic** [comment]
Node.js v22.5.1 has been released:

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#2024-07-19-version-2251-current-richardlau

Waiting for https://github.com/actions/setup-node/issues/1112

**Comment by mdjermanovic** [comment]
> We need to enable the `secrets.WORKFLOW_PUSH_BOT_TOKEN` secret for this repo

I've enabled it now.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Just waiting for the CI fix.

**Review by fasttime — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
