### PR TITLE
feat: Support ES2023 and hashbangs

### PR DESCRIPTION
**Pull request by btmills**
Acorn enabled the [hashbang grammar](https://github.com/tc39/proposal-hashbang) when `ecmaVersion` is 2023 in https://github.com/acornjs/acorn/commit/b2ecf7a378097a95c9244209cd5e4aff748c2b2c, which was released in [v8.8.0](https://github.com/acornjs/acorn/releases/tag/8.8.0).

This change adds 14/2023 as valid `ecmaVersions` (which automatically increments `latest`).

[When Acorn's constructor encounters `#!`](https://github.com/acornjs/acorn/blob/27f01d6dccfd193ee4d892140b5e5844a83f0073/acorn/src/state.js#L78-L79) at the beginning of input, it transitively calls our `onComment()` handler. I therefore needed to move Espree's `state` to before the `super()` call and make it usable before `this` is accessible.

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
LGTM

**Review by aladdin-add — CHANGES_REQUESTED** [review]
could you also update the readme: https://github.com/eslint/espree#what-ecmascript-features-do-you-support?

**Review by aladdin-add — APPROVED** [review]
👍

**Comment by mdjermanovic** [comment]
Hashbangs will have `type: "Line"`, like `//` comments. Should we maybe introduce a new comment type, e.g. `"Shebang"` (to match how ESLint works)?

**Comment by nzakas** [comment]
I’m ambivalent about the token name. On one hand, ESLint itself handles hashbangs already, and we can’t remove that functionality for backwards compatibility, so it really doesn’t matter what the token is. 

The question is more what would consumers other than ESLint expect this token to be?

**Comment by btmills** [comment]
The proposal includes a section on "[why hashbang instead of shebang](https://github.com/tc39/proposal-hashbang#why-hashbang-instead-of-shebang)". Since ESLint's precedent of calling it `"Shebang"` is less relevant here, I went with `"Hashbang"` to be consistent with the proposal, which is likely what non-ESLint consumers would expect.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
